(function(){'use strict';
var F='linuxplus-v64-favorites',H='linuxplus-v64-history',M='linuxplus-v64-missed',A='linuxplus-v64-activity';
function r(k,d){try{var v=JSON.parse(localStorage.getItem(k)||'null');return v===null?d:v}catch(e){return d}}function w(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch(e){}}
function favs(){return r(F,[])}function isFavorite(id){return favs().indexOf(id)>=0}function misses(){return r(M,[])}function wasMissed(id){return misses().indexOf(id)>=0}
function day(x){x=x||new Date();return x.getFullYear()+'-'+String(x.getMonth()+1).padStart(2,'0')+'-'+String(x.getDate()).padStart(2,'0')}
function streak(){var ds=new Set(r(A,[])),n=0,d=new Date();while(ds.has(day(d))){n++;d.setDate(d.getDate()-1)}return n}
function activity(){var ds=r(A,[]),t=day();if(ds.indexOf(t)<0){ds.push(t);w(A,ds.slice(-180))}}
function recordExam(qs,ans,c,pct){activity();var h=r(H,[]);h.push({date:new Date().toISOString(),total:qs.length,correct:c,pct:pct});w(H,h.slice(-50));var m=misses();qs.forEach(function(q){var ok=(ans[q.id]||[]).slice().sort().join('|')===q.correct.slice().sort().join('|'),i=m.indexOf(q.id);if(!ok&&i<0)m.push(q.id);if(ok&&i>=0)m.splice(i,1)});w(M,m);refresh()}
function set(id,v){var e=document.getElementById(id);if(e)e.textContent=v}function refresh(){var f=favs().length,m=misses().length,h=r(H,[]),b=h.length?Math.max.apply(null,h.map(function(x){return x.pct})):'—',p=h.reduce(function(n,x){return n+(x.total||0)},0),st=streak();set('favoriteCountStart',f);set('missedCountStart',m);set('homeFavorites',f);set('homePracticed',p);set('homeBest',b==='—'?b:b+'%');set('homeStreak',st+' day'+(st===1?'':'s'));updateButton()}
function updateButton(){var b=document.getElementById('favoriteBtn');if(!b||!window.exam||!exam.length)return;var on=isFavorite(exam[idx].id);b.textContent=on?'★ Saved to Favorites':'☆ Save to Favorites';b.classList.toggle('active',on);b.setAttribute('aria-pressed',on?'true':'false')}
function toggle(id){var f=favs(),i=f.indexOf(id);if(i>=0)f.splice(i,1);else f.push(id);w(F,f);refresh()}
function run(mode,count){studyMode=mode;var c=document.getElementById('countSelect');if(c)c.value=count?String(count):'all';var sh=document.getElementById('shuffleQuestions');if(sh)sh.checked=true;var ok=internalBegin();studyMode='normal';return ok}
window.LP64={isFavorite:isFavorite,wasMissed:wasMissed,recordExam:recordExam,refreshDashboard:refresh};var base=window.render;window.render=function(){base();updateButton()};
document.addEventListener('DOMContentLoaded',function(){var b=document.getElementById('favoriteBtn');if(b)b.onclick=function(){if(exam&&exam.length)toggle(exam[idx].id)};document.getElementById('quick10Btn').onclick=function(){run('normal',10)};document.getElementById('favoritesExamBtn').onclick=function(){if(!favs().length){setStartupStatus('Save at least one question as a favorite first.','error');return}run('favorites')};document.getElementById('missedHistoryBtn').onclick=function(){if(!misses().length){setStartupStatus('No recent missed questions are saved yet.','error');return}run('missed')};refresh()})})();