(function(){
'use strict';
var KEY='linuxplus-v70-learning-records', FKEY='linuxplus-v64-favorites';
function read(k,d){try{var v=JSON.parse(localStorage.getItem(k)||'null');return v===null?d:v}catch(e){return d}}
function write(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch(e){console.warn(e)}}
function records(){return read(KEY,{})}
function saveRecords(v){write(KEY,v)}
function favs(){return read(FKEY,[])}
function same70(a,b){return (a||[]).slice().sort().join('|')===(b||[]).slice().sort().join('|')}
function esc70(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function now(){return new Date().toISOString()}
function getRec(id){var all=records();return all[id]||{attempts:0,correctAttempts:0,incorrectAttempts:0,consecutiveCorrect:0,lastAttempted:'',note:'',mastered:false};}
function updateRec(id,patch){var all=records(),r=all[id]||{attempts:0,correctAttempts:0,incorrectAttempts:0,consecutiveCorrect:0,lastAttempted:'',note:'',mastered:false};Object.keys(patch).forEach(function(k){r[k]=patch[k]});all[id]=r;saveRecords(all);return r}
function recordAttempt(q,chosen){var all=records(),r=all[q.id]||{attempts:0,correctAttempts:0,incorrectAttempts:0,consecutiveCorrect:0,lastAttempted:'',note:'',mastered:false};var ok=same70(chosen,q.correct);r.attempts=(r.attempts||0)+1;r.lastAttempted=now();r.lastResult=ok?'correct':'incorrect';if(ok){r.correctAttempts=(r.correctAttempts||0)+1;r.consecutiveCorrect=(r.consecutiveCorrect||0)+1}else{r.incorrectAttempts=(r.incorrectAttempts||0)+1;r.consecutiveCorrect=0}r.mastered=(r.consecutiveCorrect||0)>=5;var conf=window.LP69&&LP69.getConfidence?LP69.getConfidence(q.id):'';if(conf)r.lastConfidence=conf;if(conf==='guess'&&ok)r.correctGuess=true;if(conf==='confident'&&!ok)r.highConfidenceMiss=true;all[q.id]=r;saveRecords(all)}
function bankById(){var m={};(window.BANK||[]).forEach(function(q){m[q.id]=q});return m}
function stats(){var all=records(),vals=Object.keys(all).map(function(k){return all[k]});return {tracked:vals.length,mistakes:vals.filter(function(r){return (r.incorrectAttempts||0)>0}).length,needs:vals.filter(function(r){return !r.mastered&&((r.incorrectAttempts||0)>0||r.correctGuess||r.highConfidenceMiss)}).length,mastered:vals.filter(function(r){return r.mastered}).length}}
function refreshHome(){var s=stats();setText('notebookMistakes',s.mistakes);setText('notebookNeeds',s.needs);setText('notebookMastered',s.mastered)}
function setText(id,v){var e=document.getElementById(id);if(e)e.textContent=v}
function startSet(qs,label){if(!qs.length){if(window.setStartupStatus)setStartupStatus('No questions match this Smart Review filter yet.','error');return}exam=qs.slice();answers={};checked={};idx=0;submitted=false;searchTerm='';document.getElementById('startScreen').classList.add('hidden');document.getElementById('resultsScreen').classList.add('hidden');document.getElementById('examScreen').classList.remove('hidden');var jm=document.getElementById('jumpModule');jm.innerHTML='<option value="all">All in exam</option>';Array.from(new Set(exam.map(function(q){return q.module}))).sort(function(a,b){return a-b}).forEach(function(n){jm.insertAdjacentHTML('beforeend','<option value="'+n+'">Module '+n+'</option>')});render();saveState();if(window.setStartupStatus)setStartupStatus(label+' started.','ok');window.scrollTo(0,0)}
function filtered(kind){var all=records(),bm=bankById(),ids=Object.keys(all).filter(function(id){var r=all[id];if(kind==='mistakes')return (r.incorrectAttempts||0)>0;if(kind==='needs')return !r.mastered&&((r.incorrectAttempts||0)>0||r.correctGuess||r.highConfidenceMiss);if(kind==='low-confidence')return r.lastConfidence==='guess'||r.lastConfidence==='somewhat';if(kind==='mastered')return !!r.mastered;return false});return ids.map(function(id){return bm[id]}).filter(Boolean)}
function addHome(){var qa=document.querySelector('.quick-actions');if(!qa||document.getElementById('mistakeNotebookBtn'))return;var b=document.createElement('button');b.type='button';b.className='btn';b.id='mistakeNotebookBtn';b.innerHTML='📓 Mistake Notebook <span id="notebookMistakes">0</span>';qa.appendChild(b);b.onclick=openNotebook;
var dash=document.querySelector('.home-dashboard');if(dash){dash.insertAdjacentHTML('beforeend','<div class="dash-card">Needs practice<strong id="notebookNeeds">0</strong></div><div class="dash-card">Mastered questions<strong id="notebookMastered">0</strong></div>')}
}
function notebookRows(kind,search){var bm=bankById(),all=records(),favorites=favs();return Object.keys(all).map(function(id){var q=bm[id],r=all[id];return q?{q:q,r:r,favorite:favorites.indexOf(id)>=0}:null}).filter(Boolean).filter(function(x){if(kind==='mistakes'&&!(x.r.incorrectAttempts>0))return false;if(kind==='needs'&&(x.r.mastered||!(x.r.incorrectAttempts>0||x.r.correctGuess||x.r.highConfidenceMiss)))return false;if(kind==='favorites'&&!x.favorite)return false;if(kind==='mastered'&&!x.r.mastered)return false;var s=(search||'').toLowerCase();return !s||(x.q.stem+' '+x.q.moduleTitle+' '+(x.r.note||'')).toLowerCase().indexOf(s)>=0}).sort(function(a,b){return (b.r.incorrectAttempts||0)-(a.r.incorrectAttempts||0)||String(b.r.lastAttempted).localeCompare(String(a.r.lastAttempted))})}
function renderNotebook(){var dlg=document.getElementById('notebookDialog');if(!dlg)return;var kind=document.getElementById('notebookFilter').value,search=document.getElementById('notebookSearch').value,rows=notebookRows(kind,search);document.getElementById('notebookCount').textContent=rows.length+' question'+(rows.length===1?'':'s');document.getElementById('notebookList').innerHTML=rows.length?rows.map(function(x){var r=x.r,q=x.q;return '<article class="notebook-item"><div class="notebook-item-head"><strong>Module '+q.module+' · Question '+q.number+'</strong><span class="mastery-pill '+(r.mastered?'mastered':'learning')+'">'+(r.mastered?'Mastered':(r.consecutiveCorrect||0)+'/5 correct streak')+'</span></div><p>'+esc70(q.stem)+'</p><div class="notebook-metrics"><span>Attempts: '+(r.attempts||0)+'</span><span>Misses: '+(r.incorrectAttempts||0)+'</span><span>Correct: '+(r.correctAttempts||0)+'</span><span>Last: '+(r.lastAttempted?new Date(r.lastAttempted).toLocaleDateString():'—')+'</span></div><label>Personal note<textarea class="notebook-note" data-id="'+q.id+'" placeholder="Add your memory tip or reminder">'+esc70(r.note||'')+'</textarea></label><div class="notebook-item-actions"><button class="btn practice-one" data-id="'+q.id+'">Practice</button><button class="btn toggle-mastery" data-id="'+q.id+'">'+(r.mastered?'Mark Learning':'Mark Mastered')+'</button></div></article>'}).join(''):'<div class="empty-notebook">No questions match this filter yet.</div>';
document.querySelectorAll('.notebook-note').forEach(function(t){t.onchange=function(){updateRec(t.dataset.id,{note:t.value})}});document.querySelectorAll('.practice-one').forEach(function(b){b.onclick=function(){var q=bankById()[b.dataset.id];closeNotebook();startSet([q],'Single-question practice')}});document.querySelectorAll('.toggle-mastery').forEach(function(b){b.onclick=function(){var r=getRec(b.dataset.id);updateRec(b.dataset.id,{mastered:!r.mastered,consecutiveCorrect:!r.mastered?5:0});renderNotebook();refreshHome()}})}
function openNotebook(){var old=document.getElementById('notebookDialog');if(old){old.classList.remove('hidden');renderNotebook();return}var wrap=document.createElement('div');wrap.id='notebookDialog';wrap.className='notebook-backdrop';wrap.innerHTML='<section class="notebook-panel" role="dialog" aria-modal="true" aria-labelledby="notebookTitle"><div class="notebook-header"><div><h2 id="notebookTitle">Mistake Notebook & Smart Favorites</h2><p>Review misses, notes, confidence gaps, and mastery progress.</p></div><button class="btn" id="closeNotebook">Close</button></div><div class="notebook-controls"><select id="notebookFilter"><option value="needs">Needs Practice</option><option value="mistakes">All Mistakes</option><option value="favorites">Favorites with History</option><option value="mastered">Mastered</option><option value="all">All Tracked</option></select><input id="notebookSearch" type="search" placeholder="Search questions or notes"><span id="notebookCount"></span></div><div class="smart-review-actions"><button class="btn primary" id="practiceNeeds">Practice Needs Review</button><button class="btn" id="practiceMistakes">Practice Mistakes</button><button class="btn" id="practiceLowConfidence">Practice Low Confidence</button></div><div id="notebookList" class="notebook-list"></div></section>';document.body.appendChild(wrap);document.getElementById('closeNotebook').onclick=closeNotebook;wrap.onclick=function(e){if(e.target===wrap)closeNotebook()};document.getElementById('notebookFilter').onchange=renderNotebook;document.getElementById('notebookSearch').oninput=renderNotebook;document.getElementById('practiceNeeds').onclick=function(){var qs=filtered('needs');closeNotebook();startSet(qs,'Needs-practice review')};document.getElementById('practiceMistakes').onclick=function(){var qs=filtered('mistakes');closeNotebook();startSet(qs,'Mistake review')};document.getElementById('practiceLowConfidence').onclick=function(){var qs=filtered('low-confidence');closeNotebook();startSet(qs,'Low-confidence review')};renderNotebook()}
function closeNotebook(){var e=document.getElementById('notebookDialog');if(e)e.classList.add('hidden')}
function addQuestionNote(){var tools=document.querySelector('.question-tools');if(!tools||document.getElementById('questionNoteBtn'))return;var b=document.createElement('button');b.className='btn';b.type='button';b.id='questionNoteBtn';b.textContent='📝 Note';tools.insertBefore(b,document.getElementById('exitExamBtn'));b.onclick=function(){if(!exam||!exam[idx])return;var q=exam[idx],r=getRec(q.id),note=prompt('Personal note for this question:',r.note||'');if(note!==null){updateRec(q.id,{note:note});b.classList.toggle('active',!!note)}}}
function refreshQuestionNote(){var b=document.getElementById('questionNoteBtn');if(b&&exam&&exam[idx]){var r=getRec(exam[idx].id);b.textContent=r.note?'📝 Note Saved':'📝 Note';b.classList.toggle('active',!!r.note)}}
var baseRender=window.render;window.render=function(){baseRender.apply(this,arguments);addQuestionNote();refreshQuestionNote()};
var recordedThisAttempt={};
var submit=document.getElementById('submitExam');if(submit)submit.addEventListener('click',function(){setTimeout(function(){if(typeof submitted!=='undefined'&&submitted){exam.forEach(function(q){if(!recordedThisAttempt[q.id]){recordAttempt(q,answers[q.id]||[]);recordedThisAttempt[q.id]=true}});refreshHome()}},0)},true);
// Record checked answers once per answer selection and avoid recounting at final grading.
var seenCheck={};var check=document.getElementById('checkBtn');if(check)check.addEventListener('click',function(){setTimeout(function(){if(!exam||!exam[idx])return;var q=exam[idx],sig=(answers[q.id]||[]).slice().sort().join('|');if(!sig)return;var key=q.id+'|'+sig;if(seenCheck[key])return;seenCheck[key]=true;recordAttempt(q,answers[q.id]||[]);recordedThisAttempt[q.id]=true;refreshHome()},0)});
addHome();addQuestionNote();refreshHome();
window.LP70={version:'7.0',records:records,openNotebook:openNotebook,startNeedsReview:function(){startSet(filtered('needs'),'Needs-practice review')}};
})();
