const CACHE_NAME = "linuxplus-trainer-pwa-v1";
const APP_FILES = [
  "./START_HERE_iPhone.html",
  "./assets/m10_q10_0.jpeg",
  "./assets/m10_q12_0.jpeg",
  "./assets/m10_q14_0.jpeg",
  "./assets/m10_q15_0.jpeg",
  "./assets/m10_q19_0.jpeg",
  "./assets/m10_q23_0.jpeg",
  "./assets/m10_q24_0.jpeg",
  "./assets/m10_q25_0.jpeg",
  "./assets/m10_q5_0.jpeg",
  "./assets/m10_q6_0.jpeg",
  "./assets/m10_q7_0.jpeg",
  "./assets/m10_q8_0.jpeg",
  "./assets/m10_q9_0.jpeg",
  "./assets/m11_q11_0.jpeg",
  "./assets/m11_q13_0.jpeg",
  "./assets/m11_q15_0.jpeg",
  "./assets/m11_q5_0.jpeg",
  "./assets/m11_q8_0.jpeg",
  "./assets/m13_q13_0.png",
  "./assets/m13_q9_0.png",
  "./assets/m2_q12_0.jpeg",
  "./assets/m2_q7_0.jpeg",
  "./assets/m3_q2_0.jpeg",
  "./assets/m3_q3_0.jpeg",
  "./assets/m3_q4_0.jpeg",
  "./assets/m3_q4_1.jpeg",
  "./assets/m6_q4_0.jpeg",
  "./assets/m7_q2_0.jpeg",
  "./assets/m8_q10_0.jpeg",
  "./assets/m8_q12_0.jpeg",
  "./assets/m8_q13_0.jpeg",
  "./assets/m8_q14_0.jpeg",
  "./assets/m8_q5_0.jpeg",
  "./assets/m8_q6_0.jpeg",
  "./assets/m8_q7_0.jpeg",
  "./icons/apple-touch-icon.png",
  "./icons/icon-192.png",
  "./icons/icon-512.png",
  "./index.html",
  "./manifest.webmanifest"
];
self.addEventListener('install', event => { event.waitUntil(caches.open(CACHE_NAME).then(cache => cache.addAll(APP_FILES)).then(() => self.skipWaiting())); });
self.addEventListener('activate', event => { event.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(key => key !== CACHE_NAME).map(key => caches.delete(key)))).then(() => self.clients.claim())); });
self.addEventListener('fetch', event => { if(event.request.method !== 'GET') return; event.respondWith(caches.match(event.request).then(cached => cached || fetch(event.request).then(response => { const copy=response.clone(); caches.open(CACHE_NAME).then(cache => cache.put(event.request,copy)); return response; }).catch(() => caches.match('./index.html')))); });
